name: Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-action:
    name: Run action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci
        run: npm run build --if-present
        name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          key: ${{secrets.PEMKEY}}
          host: ${{secrets.EC2IP}}
          username: ${{secrets.USERNAME}}
          script: |
            cd leviosa-signalling-server
            sudo git pull origin
            sudo npm i
            sudo pm2 restart all

      - name: Build
        run: npm run build

      - name: Run my action
        uses: ./
